# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noiseLevels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='dateRecorded',
            field=models.CharField(default='99:99:99', max_length=100),
        ),
    ]
