# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noiseLevels', '0002_reading_daterecorded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='ruObj',
            new_name='rdObj',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='dateRecorded',
            new_name='timeRecorded',
        ),
    ]
