# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noiseLevels', '0003_auto_20170206_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='dateRecorded',
            field=models.CharField(default='00/00/00', max_length=100),
        ),
    ]
