# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableBikes', models.IntegerField(default=0)),
                ('availableStands', models.IntegerField(default=0)),
                ('percentFull', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('totalBikeStands', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='bsObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dublinBikes.BikeStation'),
        ),
    ]
