# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusynessSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busynessFactor', models.FloatField(default=0.0)),
                ('average', models.FloatField(default=0.0)),
                ('dateTaken', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='busynesssub',
            name='dataObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DatasetObject'),
        ),
    ]
