# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusynessIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busyness', models.FloatField(default=0.0)),
                ('dateTaken', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
