# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_busynessindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busynesssub',
            name='average',
        ),
    ]
