# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carParks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cp',
            name='pub_date',
        ),
    ]
