# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carParks', '0002_remove_cp_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitylevel',
            name='dateTaken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='capacitylevel',
            name='name',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cp',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
