# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, null=True)),
                ('traveltime', models.IntegerField(default=0)),
                ('dateTaken', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rfrom', models.CharField(max_length=100)),
                ('rto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='ruObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m50times.Route'),
        ),
    ]
